### ISSUE TITLE
Todo: 

### ISSUE THREAD

**Issue by CThuleHansen** [into-cps/INTO-CML-FMI#2]
- [ ] Add error handling
- [ ] Add topological sort (necessary?)
- [ ] Add set/get directional deritivates (necessary?)
- [ ] Add rollback
- [ ] Add GetMaxStepSize
- [ ] Add get/set i initialization mode
